# Generated by Django 4.1.6 on 2023-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_fridge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pantry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("category", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
                ("exp_date", models.DateField(null=True)),
            ],
        ),
    ]
