# Generated by Django 4.1.6 on 2023-02-27 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taprootapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFlavor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRestriction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('source', models.URLField()),
                ('image', models.ImageField(upload_to='recipe_images/')),
                ('cuisine', models.ManyToManyField(choices=[('None', 'None'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('French', 'French'), ('Greek', 'Greek'), ('Thai', 'Thai'), ('Brazilian', 'Brazilian'), ('Korean', 'Korean'), ('Middle Eastern', 'Middle Eastern'), ('Mediterranean', 'Mediterranean'), ('Caribbean', 'Caribbean'), ('African', 'African'), ('Asian', 'Asian'), ('American', 'American'), ('Australian', 'Australian'), ('European', 'European'), ('Pacific Islander', 'Pacific Islander'), ('Other', 'Other')], default='None', to='taprootapp.recipecuisine')),
                ('flavor_profile', models.ManyToManyField(choices=[('None', 'None'), ('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Salty', 'Salty'), ('Sour', 'Sour'), ('Umami', 'Umami'), ('Herbaceous', 'Herbaceous'), ('Earthy', 'Earthy'), ('Nutty', 'Nutty'), ('Smoky', 'Smoky'), ('Other', 'Other')], default='None', to='taprootapp.recipeflavor')),
                ('restrictions', models.ManyToManyField(choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Keto', 'Keto'), ('Kosher', 'Kosher'), ('Halal', 'Halal'), ('Paleo', 'Paleo'), ('Gluten-free', 'Gluten-free'), ('Dairy-free', 'Dairy-free'), ('Nut-free', 'Nut-free'), ('Shellfish-free', 'Shellfish-free')], default='None', to='taprootapp.reciperestriction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Grains', 'Grains'), ('Canned Foods', 'Canned Foods'), ('Baking Supplies', 'Baking Supplies'), ('Spices', 'Spices'), ('Snacks', 'Snacks'), ('Sauces', 'Sauces'), ('Oil and Vinegars', 'Oil and Vinegars'), ('Sweeteners', 'Sweeteners')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Grains', 'Grains'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Dessert', 'Dessert'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
