# Generated by Django 4.1.6 on 2023-03-02 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taprootapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('none', 'None'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('french', 'French'), ('greek', 'Greek'), ('thai', 'Thai'), ('brazilian', 'Brazilian'), ('korean', 'Korean'), ('middle Eastern', 'Middle Eastern'), ('mediterranean', 'Mediterranean'), ('caribbean', 'Caribbean'), ('african', 'African'), ('asian', 'Asian'), ('american', 'American'), ('australian', 'Australian'), ('european', 'European'), ('pacific Islander', 'Pacific Islander'), ('other', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('none', 'None'), ('sweet', 'Sweet'), ('spicy', 'Spicy'), ('salty', 'Salty'), ('sour', 'Sour'), ('umami', 'Umami'), ('herbaceous', 'Herbaceous'), ('earthy', 'Earthy'), ('nutty', 'Nutty'), ('smoky', 'Smoky'), ('other', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('paleo', 'Paleo'), ('gluten-free', 'Gluten-free'), ('dairy-free', 'Dairy-free'), ('nut-free', 'Nut-free'), ('shellfish-free', 'Shellfish-free')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('source', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='recipe_images/')),
                ('cuisine', models.ManyToManyField(choices=[('none', 'None'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('french', 'French'), ('greek', 'Greek'), ('thai', 'Thai'), ('brazilian', 'Brazilian'), ('korean', 'Korean'), ('middle Eastern', 'Middle Eastern'), ('mediterranean', 'Mediterranean'), ('caribbean', 'Caribbean'), ('african', 'African'), ('asian', 'Asian'), ('american', 'American'), ('australian', 'Australian'), ('european', 'European'), ('pacific Islander', 'Pacific Islander'), ('other', 'Other')], default='none', to='taprootapp.recipecuisine')),
                ('flavor_profile', models.ManyToManyField(choices=[('none', 'None'), ('sweet', 'Sweet'), ('spicy', 'Spicy'), ('salty', 'Salty'), ('sour', 'Sour'), ('umami', 'Umami'), ('herbaceous', 'Herbaceous'), ('earthy', 'Earthy'), ('nutty', 'Nutty'), ('smoky', 'Smoky'), ('other', 'Other')], default='none', to='taprootapp.recipeflavor')),
                ('restrictions', models.ManyToManyField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('paleo', 'Paleo'), ('gluten-free', 'Gluten-free'), ('dairy-free', 'Dairy-free'), ('nut-free', 'Nut-free'), ('shellfish-free', 'Shellfish-free')], default='none', to='taprootapp.reciperestriction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Grains', 'Grains'), ('Canned Foods', 'Canned Foods'), ('Baking Supplies', 'Baking Supplies'), ('Spices', 'Spices'), ('Snacks', 'Snacks'), ('Sauces', 'Sauces'), ('Oil and Vinegars', 'Oil and Vinegars'), ('Sweeteners', 'Sweeteners')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Grains', 'Grains'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('Dessert', 'Dessert'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
