# Generated by Django 4.1.6 on 2023-03-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taprootapp', '0002_recipecuisine_recipeflavor_reciperestriction_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecuisine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeflavor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reciperestriction',
            name='name',
        ),
        migrations.AlterField(
            model_name='recipecuisine',
            name='id',
            field=models.CharField(choices=[('none', 'None'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('indian', 'Indian'), ('french', 'French'), ('greek', 'Greek'), ('thai', 'Thai'), ('brazilian', 'Brazilian'), ('korean', 'Korean'), ('middle Eastern', 'Middle Eastern'), ('mediterranean', 'Mediterranean'), ('caribbean', 'Caribbean'), ('african', 'African'), ('asian', 'Asian'), ('american', 'American'), ('australian', 'Australian'), ('european', 'European'), ('pacific Islander', 'Pacific Islander'), ('other', 'Other')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipeflavor',
            name='id',
            field=models.CharField(choices=[('none', 'None'), ('sweet', 'Sweet'), ('spicy', 'Spicy'), ('salty', 'Salty'), ('sour', 'Sour'), ('umami', 'Umami'), ('herbaceous', 'Herbaceous'), ('earthy', 'Earthy'), ('nutty', 'Nutty'), ('smoky', 'Smoky'), ('other', 'Other')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reciperestriction',
            name='id',
            field=models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('paleo', 'Paleo'), ('gluten-free', 'Gluten-free'), ('dairy-free', 'Dairy-free'), ('nut-free', 'Nut-free'), ('shellfish-free', 'Shellfish-free')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
