# Generated by Django 4.1.6 on 2023-03-03 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taprootapp", "0002_recipe_pantryitem_fridgeitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                validators=[django.core.validators.RegexValidator("^[a-zA-Z ,-]*$")]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z -]*$")],
            ),
        ),
    ]
