# Generated by Django 4.1.6 on 2023-02-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taprootapp', '0002_recipecuisine_recipeflavor_reciperestriction_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecuisine',
            name='id',
            field=models.CharField(choices=[('None', 'None'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('French', 'French'), ('Greek', 'Greek'), ('Thai', 'Thai'), ('Brazilian', 'Brazilian'), ('Korean', 'Korean'), ('Middle Eastern', 'Middle Eastern'), ('Mediterranean', 'Mediterranean'), ('Caribbean', 'Caribbean'), ('African', 'African'), ('Asian', 'Asian'), ('American', 'American'), ('Australian', 'Australian'), ('European', 'European'), ('Pacific Islander', 'Pacific Islander'), ('Other', 'Other')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipeflavor',
            name='id',
            field=models.CharField(choices=[('None', 'None'), ('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Salty', 'Salty'), ('Sour', 'Sour'), ('Umami', 'Umami'), ('Herbaceous', 'Herbaceous'), ('Earthy', 'Earthy'), ('Nutty', 'Nutty'), ('Smoky', 'Smoky'), ('Other', 'Other')], max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reciperestriction',
            name='id',
            field=models.CharField(choices=[('None', 'None'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Keto', 'Keto'), ('Kosher', 'Kosher'), ('Halal', 'Halal'), ('Paleo', 'Paleo'), ('Gluten-free', 'Gluten-free'), ('Dairy-free', 'Dairy-free'), ('Nut-free', 'Nut-free'), ('Shellfish-free', 'Shellfish-free')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
