# Generated by Django 4.1.6 on 2023-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taprootapp", "0003_alter_recipecuisine_id_alter_recipeflavor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cuisine",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="taprootapp.recipecuisine"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="flavor_profile",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="taprootapp.recipeflavor"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, upload_to="recipe_images/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="restrictions",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="taprootapp.reciperestriction"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="source",
            field=models.URLField(blank=True),
        ),
    ]
