# Generated by Django 4.1.6 on 2023-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taprootapp", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, upload_to="recipe_images/"),
        ),
    ]
