# Generated by Django 4.1.6 on 2023-02-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taproot", "0002_alter_fridgeitem_category_alter_pantryitem_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fridgeitem",
            name="id",
        ),
        migrations.RemoveField(
            model_name="pantryitem",
            name="id",
        ),
        migrations.AlterField(
            model_name="fridgeitem",
            name="item_name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pantryitem",
            name="item_name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
