# Generated by Django 4.1.6 on 2023-02-09 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taproot', '0003_remove_fridgeitem_user_remove_pantryitem_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='recipe_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Grains'), ('2', 'Canned Foods'), ('3', 'Baking Supplies'), ('4', 'Spices'), ('5', 'Snacks'), ('6', 'Sauces'), ('7', 'Oil and Vinegars'), ('8', 'Sweeteners')], max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Fruits'), ('2', 'Vegetables'), ('3', 'Grains'), ('4', 'Dairy'), ('5', 'Meat'), ('6', 'Seafood'), ('7', 'Dessert'), ('8', 'Snacks'), ('9', 'Beverages')], max_length=20, unique=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
