# Generated by Django 4.1.6 on 2023-02-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taproot", "0003_remove_fridgeitem_id_remove_pantryitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridgeitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fruits", "Fruits"),
                    ("Vegetables", "Vegetables"),
                    ("Grains", "Grains"),
                    ("Dairy", "Dairy"),
                    ("Meat", "Meat"),
                    ("Seafood", "Seafood"),
                    ("Dessert", "Dessert"),
                    ("Snacks", "Snacks"),
                    ("Beverages", "Beverages"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pantryitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Grains", "Grains"),
                    ("Canned Foods", "Canned Foods"),
                    ("Baking Supplies", "Baking Supplies"),
                    ("Spices", "Spices"),
                    ("Snacks", "Snacks"),
                    ("Sauces", "Sauces"),
                    ("Oil and Vinegars", "Oil and Vinegars"),
                    ("Sweeteners", "Sweeteners"),
                ],
                max_length=20,
            ),
        ),
    ]
