name: Add pull requests to project

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/CSC394-FoodTeam/projects/2
          github-token: ${{ secrets.WORKFLOW }}
          labeled: needs-review, invalid
          label-operator: OR
